ProjectCRM/urls.py
from django.conf.urls import re_path, include
from django.contrib import admin
from ProjectCRM import views

urlpatterns = [
    re_path(r"^$", views.index),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^account/login/$', views.acc_login),
    re_path(r'^account/logout/', views.acc_logout, name="acc_logout"),
    re_path(r'^create/', views.create),
    re_path(r'^crm/', include("crm.urls")),
    re_path(r'^student/', include("student.urls")),
    re_path(r'^useradmin/', include("king_admin.urls")),
]

crm/urls.py
from django.conf.urls import re_path
from crm import views

urlpatterns = [
    re_path(r'^$', views.index, name="sales_index"),
    re_path(r'^customer/(\d+)/enrollment/$', views.enrollment, name="enrollment"),
    re_path(r'^enrollment_rejection/(\d+)/', views.enrollment_rejection, name="enrollment_rejection"),
    re_path(r'^customers/$', views.customer_list, name="customer_list"),
    re_path(r'^customer/registration/(\d+)/(\w+)/', views.stu_registration, name="stu_registration"),
    re_path(r'^contract_review/(\d+)/', views.contract_review, name="contract_review"),
    re_path(r'^payment/(\d+)/', views.payment, name="payment"),

]

student/urls.py
from django.conf.urls import re_path
from student import views

urlpatterns = [
    re_path(r'^$', views.stu_my_classes, name="stu_my_classes"),
    re_path(r'^studyrecords/(\d+)/$', views.studyrecords, name="studyrecords"),
    re_path(r'^homework_detail/(\d+)/$', views.homework_detail, name="homework_detail"),
]

crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

class Customer(models.Model):
    name = models.CharField(max_length=32, blank=True, null=True, help_text="用户报名后改名")
    qq = models.CharField(max_length=64, unique=True)
    qq_name = models.CharField(max_length=64, blank=True, null=True)
    phone = models.CharField(max_length=64, blank=True, null=True)
    id_num = models.CharField(max_length=64, blank=True, null=True)
    email = models.EmailField(verbose_name="常用邮箱", blank=True, null=True)
    source_choices = ((0, '转介绍'),
                      (1, 'QQ群'),
                      (2, '官网'),
                      (3, '百度推广'),
                      (4, '51CTO'),
                      (5, '知乎'),
                      (6, '市场推广'),
                      )

    source = models.SmallIntegerField(choices=source_choices)
    referral_from = models.CharField(verbose_name="转介绍人qq", max_length=64, blank=True, null=True)

    consult_course = models.ForeignKey("Course", verbose_name="咨询课程", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="咨询详情")
    tags = models.ManyToManyField("Tag", blank=True, )
    status_choices = ((0, '已报名'),
                      (1, '未报名'),
                      )
    status = models.SmallIntegerField(choices=status_choices, default=1)
    consultant = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    memo = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s" % (self.qq, self.name)

    class Meta:
        verbose_name = "客户表"
        verbose_name_plural = "客户表"

class Tag(models.Model):
    name = models.CharField(unique=True, max_length=32)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"


class CustomerFollowUp(models.Model):
    '''客户跟进表'''
    customer = models.ForeignKey("Customer", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="跟进内容")
    consultant = models.ForeignKey("UserProfile", on_delete=models.CASCADE)

    intention_choices = ((0, '2周内报名'),
                         (1, '1个月内报名'),
                         (2, '近期无报名计划'),
                         (3, '已在其它机构报名'),
                         (4, '已报名'),
                         (5, '已拉黑'),
                         )
    intention = models.SmallIntegerField(choices=intention_choices)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "<%s : %s>" % (self.customer.qq, self.intention)

    class Meta:
        verbose_name = "客户跟进记录"
        verbose_name_plural = "客户跟进记录"

class Course(models.Model):
    '''课程表'''
    name = models.CharField(max_length=64, unique=True)
    price = models.PositiveSmallIntegerField()
    period = models.PositiveSmallIntegerField(verbose_name="周期(月)")
    outline = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "课程表"
        verbose_name_plural = "课程表"

class Branch(models.Model):
    '''校区'''
    name = models.CharField(max_length=128, unique=True)
    addr = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "校区"
        verbose_name_plural = "校区"


class ClassList(models.Model):
    '''班级表'''
    branch = models.ForeignKey("Branch", verbose_name="校区", on_delete=models.CASCADE)
    course = models.ForeignKey("Course", on_delete=models.CASCADE)
    class_type_choices = ((0, '面授(脱产)'),
                          (1, '面授(周末)'),
                          (2, '网络班')
                          )
    contract = models.ForeignKey("ContractTemplate", blank=True, null=True, on_delete=callable)

    class_type = models.SmallIntegerField(choices=class_type_choices, verbose_name="班级类型")
    semester = models.PositiveSmallIntegerField(verbose_name="学期")
    teachers = models.ManyToManyField("UserProfile")
    start_date = models.DateField(verbose_name="开班日期")
    end_date = models.DateField(verbose_name="结业日期", blank=True, null=True)

    def __str__(self):
        return "%s %s %s" % (self.branch, self.course, self.semester)

    class Meta:
        unique_together = ('branch', 'course', 'semester')
        verbose_name_plural = "班级"
        verbose_name = "班级"


class ContractTemplate(models.Model):
    '''合同模版'''
    name = models.CharField("合同名称", max_length=64, unique=True)
    template = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "合同"
        verbose_name = "合同"


class CourseRecord(models.Model):
    '''上课记录'''
    from_class = models.ForeignKey("ClassList", verbose_name="班级", on_delete=models.CASCADE)
    day_num = models.PositiveSmallIntegerField(verbose_name="第几节(天)")
    teacher = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    has_homework = models.BooleanField(default=True)
    homework_title = models.CharField(max_length=128, blank=True, null=True)
    homework_content = models.TextField(blank=True, null=True)
    outline = models.TextField(verbose_name="本节课程大纲")
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s" % (self.from_class, self.day_num)

    class Meta:
        unique_together = ("from_class", "day_num")
        verbose_name_plural = "上课记录"
        verbose_name = "上课记录"


class StudyRecord(models.Model):
    '''学习记录'''
    student = models.ForeignKey("Enrollment", on_delete=models.CASCADE)
    course_record = models.ForeignKey("CourseRecord", on_delete=models.CASCADE)
    attendance_choices = ((0, '已签到'),
                          (1, '迟到'),
                          (2, '缺勤'),
                          (3, '早退'),
                          )
    attendance = models.SmallIntegerField(choices=attendance_choices, default=0)
    score_choices = ((100, "A+"),
                     (90, "A"),
                     (85, "B+"),
                     (80, "B"),
                     (75, "B-"),
                     (70, "C+"),
                     (60, "C"),
                     (40, "C-"),
                     (-50, "D"),
                     (-100, "COPY"),
                     (0, "N/A"),
                     )
    score = models.SmallIntegerField(choices=score_choices, default=0)
    memo = models.TextField(blank=True, null=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s %s" % (self.student, self.course_record, self.score)

    class Meta:
        unique_together = ('student', 'course_record')
        verbose_name = "学生学习记录"
        verbose_name_plural = "学生学习记录"


class Enrollment(models.Model):
    '''报名表'''
    customer = models.ForeignKey("Customer", on_delete=models.CASCADE)
    enrolled_class = models.ForeignKey("ClassList", verbose_name="所报班级", on_delete=models.CASCADE)
    consultant = models.ForeignKey("UserProfile", verbose_name="课程顾问", on_delete=models.CASCADE)
    contract_agreed = models.BooleanField(default=False, verbose_name="学员已同意合同条款")
    contract_approved = models.BooleanField(default=False, verbose_name="合同已审核")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s" % (self.customer, self.enrolled_class)

    class Meta:
        unique_together = ("customer", "enrolled_class")
        verbose_name_plural = "报名表"
        verbose_name = "报名表"

class Payment(models.Model):
    '''缴费记录'''
    customer = models.ForeignKey("Customer", on_delete=models.CASCADE)
    course = models.ForeignKey("Course", verbose_name="所报课程", on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(verbose_name="数额", default=500)
    consultant = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s" % (self.customer, self.amount)

    class Meta:
        verbose_name_plural = "缴费记录"
        verbose_name = "缴费记录"

class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        self.is_active = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email=email,
            password=password,
            name=name,
        )
        user.is_active = True
        user.is_admin = True
        user.save(using=self._db)
        return user

class UserProfile(AbstractBaseUser, PermissionsMixin):
    '''账号表'''

    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
        null=True
    )
    password = models.CharField(('password'), max_length=128, help_text=mark_safe('''<a href='password/'>修改密码</a>'''))
    name = models.CharField(max_length=32)
    # roles = models.ManyToManyField("Role", blank=True)
    # is_active = models.BooleanField(default=True)
    # is_admin = models.BooleanField(default=False)
    # objects = UserProfileManager()
    # stu_account = models.ForeignKey("Customer", verbose_name="关联学员账号", blank=True, null=True,
    #                                 help_text="只有学员报名后方可为其创建账号", on_delete=models.CASCADE)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = '用户信息'

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render, HttpResponse
from crm import models
from ProjectCRM import settings
import os, json, time
from crm.permissions import permission

@permission.check_permission
def stu_my_classes(request):
    return render(request, "student/my_classes.html")

@permission.check_permission
def studyrecords(request, enroll_obj_id):
    enroll_obj = models.Enrollment.objects.get(id=enroll_obj_id)
    return render(request, "student/studyrecords.html", {"enroll_obj": enroll_obj})

@permission.check_permission
def homework_detail(request, studyrecord_id):
    studyrecord_obj = models.StudyRecord.objects.get(id=studyrecord_id)
    homework_path = "{base_dir}/{class_id}/{course_record_id}/{studyrecord_id}/" \
        .format(base_dir=settings.HOMEWORK_DATA,
                class_id=studyrecord_obj.student.enrolled_class_id,
                course_record_id=studyrecord_obj.course_record_id,
                studyrecord_id=studyrecord_obj.id
                )
    if not os.path.isdir(homework_path):
        os.makedirs(homework_path, exist_ok=True)

    if request.method == "POST":
        for k, file_obj in request.FILES.items():
            with open("%s/%s" % (homework_path, file_obj.name), "wb") as f:
                for chunk in file_obj.chunks():
                    f.write(chunk)
    file_lists = []
    for file_name in os.listdir(homework_path):
        f_path = "%s/%s" % (homework_path, file_name)
        modify_time = time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(os.stat(f_path).st_mtime))
        file_lists.append([file_name, os.stat(f_path).st_size, modify_time])

    if request.method == "POST":
        return HttpResponse(json.dumps({"status": 0,
                                        "msg": "file upload success",
                                        'file_lists': file_lists}))
    return render(request, "student/homework_detail.html",
                  {"studyrecord_obj": studyrecord_obj,
                   "file_lists": file_lists})

templates/student/homework_detail.html
{%  extends 'index.html' %}
{% load stu_tags %}

{% block page-content %}
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">班级:{{ studyrecord_obj.student.enrolled_class }}  | 节次{{ studyrecord_obj.course_record.day_num }}</div>
  <div class="panel-body">
        <h4>作业标题:{{ studyrecord_obj.course_record.homework_title }}</h4>
        <h4>作业详情：<pre>{{ studyrecord_obj.course_record.homework_content }}</pre></h4>
        <h4>老师评语:{{ studyrecord_obj.memo }}</h4>
        <h4>本节成绩:{{ studyrecord_obj.score }}</h4>
        <div class="row">
            <p>已上传作业</p>
            <ul>
                {% for file in file_lists %}
                <li>{{ file.0 }} | {{ file.1 }} | {{ file.2 }}</li>
                {% endfor %}
            </ul>

        </div>
        <form id="filedropzone" method="post" action="{{ request.path }}" class="dropzone dz-clickable" >
            {% csrf_token %}
            <div class="dz-default dz-message">
                <div class="dz-icon icon-wrap icon-circle icon-wrap-md">
                    <i class="fa fa-cloud-upload fa-3x"></i>
                </div>
                <div>
                    <p class="dz-text">把证件信息拖放到这里</p>
                    <p class="text-muted">最多可上传2张照片</p>
                </div>
            </div>
        </form>

  </div>
  <!-- Table -->
</div>
{% endblock %}

{% block bottom-js %}
<script>
    $(document).ready(function () {
         Dropzone.options.filedropzone = {
          url:"{{ request.path }}",
          paramName: "file", // The name that will be used to transfer the file
          maxFilesize: 1, // MB,
          addRemoveLinks:true,
          maxFiles:5,
          uploadMultiple:true,
          accept: function(file, done) {
            if (! file.name.endsWith(".zip") ) {
              alert("只能上传.zip格式的压缩包")
                done("文件为上传")
                myDropzone.removeFile(file);
            }
            else { done(); }
          }
        };

      Dropzone.autoDiscover = false;
      myDropzone = new Dropzone("#filedropzone");
      myDropzone.on("addedfile", function(file) {
        /* Maybe display some more file information on your page */
        console.log("-------",file)
      });

      myDropzone.on("success", function(file,response) {
          /* Maybe display some more file information on your page */
          console.log('files upload done...', response);
      } )

    })
</script>
{% endblock %}

templates/student/my_classes.html
{%  extends 'index.html' %}
{% load stu_tags %}

{% block page-content %}
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">我的课程</div>
  <div class="panel-body">
     <table class="table table-striped table-responsive">
      <thead>
        <tr>
            <th>课程名称</th>
            <th>班级</th>
            <th>开课日期</th>
            <th>结业日期</th>
            <th>课程进度</th>
            <th>我的成绩</th>
            <th>作业管理</th>
        </tr>
      </thead>
      <tbody>
        {% for enroll_obj in request.user.stu_account.enrollment_set.all %}
            <tr>
                <td>{{ enroll_obj.enrolled_class.course }}</td>
                <td>s{{ enroll_obj.enrolled_class.semester }}</td>
                <td>{{ enroll_obj.enrolled_class.start_date }}</td>
                <td>{{ enroll_obj.enrolled_class.end_date }}</td>
                <td>已上{{ enroll_obj.enrolled_class.courserecord_set.all.count }}节</td>
                <td>{% get_score enroll_obj request.user.stu_account as score_data %}
                    {{ score_data.score__sum }}
                </td>
                <td><a href="{% url 'studyrecords' enroll_obj.id %}">作业管理</a></td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/student/studyrecords.html
{%  extends 'index.html' %}
{% load stu_tags %}
{% block page-content %}

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ enroll_obj.enrolled_class }}</div>
  <div class="panel-body">
     <table class="table table-striped table-responsive">
      <thead>
        <tr>
            <th>课程节次</th>
            <th>上课日期</th>
            <th>是否有作业</th>
            <th>作业标题</th>
            <th>签到状态</th>
            <th>成绩</th>
            <th>作业详情</th>
        </tr>
      </thead>
      <tbody>
            {% for studyrecord in enroll_obj.studyrecord_set.all %}
            <tr>
                <td>{{ studyrecord.course_record.day_num }}</td>
                <td>{{ studyrecord.course_record.date }}</td>
                <td>{{ studyrecord.course_record.has_homework }}</td>
                <td>{{ studyrecord.course_record.homework_title }}</td>
                <td>{{ studyrecord.get_attendance_display}}</td>
                <td>{{ studyrecord.get_score_display}}</td>
                <td><a href="{% url 'homework_detail'  studyrecord.id %}">作业详情</a></td>
            </tr>
            {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- Table -->
</div>
{% endblock %}